name: Web_final
channels:
  - defaults
dependencies:
  - _libgcc_mutex=0.1=main
  - _openmp_mutex=5.1=1_gnu
  - bzip2=1.0.8=h5eee18b_6
  - ca-certificates=2025.2.25=h06a4308_0
  - expat=2.7.1=h6a678d5_0
  - ld_impl_linux-64=2.40=h12ee557_0
  - libffi=3.4.4=h6a678d5_1
  - libgcc-ng=11.2.0=h1234567_1
  - libgomp=11.2.0=h1234567_1
  - libmpdec=4.0.0=h5eee18b_0
  - libstdcxx-ng=11.2.0=h1234567_1
  - libuuid=1.41.5=h5eee18b_0
  - ncurses=6.4=h6a678d5_0
  - openssl=3.0.16=h5eee18b_0
  - pip=25.1=pyhc872135_2
  - python=3.13.2=hf623796_100_cp313
  - python_abi=3.13=0_cp313
  - readline=8.2=h5eee18b_0
  - setuptools=78.1.1=py313h06a4308_0
  - sqlite=3.45.3=h5eee18b_0
  - tk=8.6.14=h39e8969_0
  - wheel=0.45.1=py313h06a4308_0
  - xz=5.6.4=h5eee18b_1
  - zlib=1.2.13=h5eee18b_1
  - pip:
      - asgiref==3.8.1
      - certifi==2025.4.26
      - charset-normalizer==3.4.2
      - django==5.2.1
      - djangorestframework==3.16.0
      - djangorestframework-simplejwt==5.5.0
      - et-xmlfile==2.0.0
      - googlemaps==4.10.0
      - idna==3.10
      - mysqlclient==2.2.7
      - numpy==2.2.6
      - openpyxl==3.1.5
      - pandas==2.2.3
      - pyjwt==2.9.0
      - python-dateutil==2.9.0.post0
      - python-decouple==3.8
      - python-slugify==8.0.4
      - pytz==2025.2
      - requests==2.32.3
      - six==1.17.0
      - slugify==0.0.1
      - sqlparse==0.5.3
      - text-unidecode==1.3
      - tzdata==2025.2
      - urllib3==2.4.0
prefix: /home/zzzoaoqqzz/.conda/envs/Web_final
